# build on top of  base image
FROM r-base

ADD . /app

#install R packages
RUN R -e "install.packages('data.table',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('getopt',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('plyr',dependencies=TRUE, repos='http://cran.rstudio.com/')"

RUN R -e "install.packages('BiocManager',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('iranges'); library('BiocManager'); BiocManager::install('hmmcopy')"
RUN R -e "install.packages('geneplotter'); library('BiocManager'); BiocManager::install('iranges')"

RUN cp /app/hmmcopy_single_cell.R /usr/bin/

CMD ["bash"]


