# build on top of  base image
FROM conda/miniconda3

ADD . /app

# Install basic packages
RUN apt-get update && apt-get install -y libltdl7 && rm -rf /var/lib/apt/lists/*
RUN conda update -y conda

#perl and r
RUN conda install -c conda-forge -c anaconda r-base perl

# #install python packages
RUN pip install pandas
RUN pip install numpy
#
#
# #install R packages
RUN R -e "install.packages('BiocManager',dependencies=TRUE, repos='http://cran.rstudio.com/');library('BiocManager');BiocManager::install('‘HMMcopy’'); BiocManager::install('IRanges'); BiocManager::install('Rsamtools');  BiocManager::install('GenomeInfoDb'); BiocManager::install('SNPchip')"
RUN R -e "install.packages('foreach',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('argparse',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('doMC',dependencies=TRUE, repos='http://cran.rstudio.com/')"

RUN cp /app/correctReads.R /usr/bin/
RUN cp /app/plot_titan.R /usr/bin/
RUN cp /app/titan.R /usr/bin/
RUN cp /app/parse_titan_segments.py /usr/bin/

CMD ["bash"]
