FROM continuumio/miniconda

RUN conda install -c shahcompbio circos_utils
RUN conda install -c shahcompbio -c r -c conda-forge -c bioconda r==3.5.1 circos

ADD . /app

ENV NAME circos

# run R by default
CMD ["R"]

